### PR TITLE
[feature] Quick Log Out Button

### PR DESCRIPTION
**Pull request by anmode**
# Descripción
Created the logout button keeping in mind

1. The logout button shouldn't appear when the user hasn't logged in.
2. Included the fontawesome icon (power off)

Desktop:

https://user-images.githubusercontent.com/88332977/162359065-838d9ec4-1e28-4aab-b108-c40c4a315b02.mp4

Mobile:

Screenshot from 2022-04-09 07-27-37

Fixes: #6516

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by heduenas** [comment]
Can you also include a screenshot of what it looks like on mobile?

**Comment by anmode** [comment]
> Can you also include a screenshot of what it looks like on mobile?

Actually recently @MohitOhlyan sent a PR requesting to change the UI of mobile navbar.
And i think as there is project of mobile optimization so it could be better if this to be considered there.
If then you want i would fix up this logout button in mobile interface. Should i?

**Comment by anmode** [comment]
Screenshot from 2022-04-09 07-27-37
this is the look in mobile

**Comment by heduenas** [comment]
I think it'd be better to place it right next to the username in the mobile version. Can you file an issue to do that later or if it's an easy change can you do it in this same PR?

**Review by heduenas — APPROVED** [review]
LGTM

**Comment by anmode** [comment]
> I think it'd be better to place it right next to the username in the mobile version. Can you file an issue to do that later or if it's an easy change can you do it in this same PR?

I'll file as issue soon. As currently there is working on mobile navbar. #6527 
So as soon that's final I make a PR for this mobile logout button.
Thanks!

**Comment by MohitOhlyan** [comment]
You can add the `<a>` inside the  `<li>` of user `<ul>` That would fix it.

**Pull request merged**
