### PR TITLE
Modify problem edit page.

### PR DESCRIPTION
**Pull request by Aritra8438**
# Description

This pr modifies the contest edit page to imitate the course edit page.

Fixes: #5176

https://github.com/omegaup/omegaup/assets/64671908/062f7125-5e6c-48a9-bd74-d2a74d991364

# Comments

- I followed all the design aspects of the course page.
- Added href attribute for tabs.

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.
- [x] If you are creating a feature, the new tests were added.
- [x] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by Aritra8438** [comment]
Hi @pabo99, here is the PR that modifies the problem edit page.
PTAL!

Also, should I shorten any words?

**Comment by pabo99** [comment]
> Hi @pabo99, here is the PR that modifies the problem edit page. PTAL!
> 
> Also, should I shorten any words?

Thank you @Aritra8438, let me check with @tvanessa if we can shorten the words as follows:

- Edit problem > Settings
- Edit statement > Statement
- View version history > Version history
- Edit solution > Solution
- Admin > Admins
- Tags = Tags
- Download = Download

**Review by pabo99 — COMMENTED** [review]
Thank you for addressing this issue.

Now that you are more familiar with the code, could you please address the following issue in this PR:
TabSelectedFail
?

When the page is refreshed, the selected tab should remain active, similar to the behavior on the CourseEdit page:
TabSelectedOk

**Comment by Aritra8438** [comment]
> When the page is refreshed, the selected tab should remain active, similar to the behavior on the CourseEdit page

I see, then this problem might be in the contest edit page too! I will address this ASAP.

**Comment by pabo99** [comment]
> > When the page is refreshed, the selected tab should remain active, similar to the behavior on the CourseEdit page
> 
> I see, then this problem might be in the contest edit page too! I will address this ASAP.

You're right. But it has a low priority, you can create an issue and then solve it

**Comment by Aritra8438** [comment]
Hi @pabo99, I have addressed the issue for the problem-edit page in this pr. For the contest-edit page, I will create a dedicated issue and pr.
PTAL!

**Review by pabo99 — APPROVED** [review]
Excellent!

**Review by heduenas — APPROVED** [review]

**Pull request merged**
