### PR TITLE
added skeleton loader while submission of problem

### PR DESCRIPTION
**Pull request by antedotee**
# Description

Earlier,user was unable to know whether the code is running or not.So,I added a skeleton loader and its component so that user can know that program is running.

Fixes: #7492

# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Review by pabo99 — COMMENTED** [review]
I've left you some suggestions. 

Additionally, while this change is not directly related to the assigned issue, I believe it is necessary. 

To address this properly, I suggest creating a new issue specifically for this change and then linking it accordingly.

**Review by pabo99 — COMMENTED** [review]
could you please run:

```
./stuff/lint.sh
```
?

This way is easier adding a review

**Comment by pabo99** [comment]
We recommend not using `main` branch, It would be better using a new branch and then push your changes related to an specific issue.

**Comment by antedotee** [comment]
I am extremely sorry for my mistake,I won't repeat this again.In next PR,I will do what you just told.

**Pull request closed without merging**
