### PR TITLE
use correct variable

### PR DESCRIPTION
**Pull request by HNOONa-0**
# Description

I was using incorrect variable name when updating the templates. The `extension` variable is the correct one.

https://github.com/user-attachments/assets/63f0342d-c75b-4988-8a57-38af20480147

Fixes: #7827 

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.

### CODE REVIEW

**Comment by HNOONa-0** [comment]
@heduenas PTAL!

**Review by pabo99 — COMMENTED** [review]
Is it possible to add a test in order to validate the template’s value?

**Review by pabo99 — APPROVED** [review]
Thank you so much, @HNOONa-0!

**Review by heduenas — APPROVED** [review]

**Comment by heduenas** [comment]
@HNOONa-0 can you please resolve the merge conflicts?

**Pull request merged**
