### PR TITLE
Search bar z index

### PR DESCRIPTION
**Pull request by iqbalcodes6602**
# Descripción

Removed the z-index style attribute which was making it display over  all other elements

image

Si tu cambio toca la interfaz, hay que incluir una captura de pantalla.

Fixes: #7423 

# Comentarios

Si hay comentarios para los reviewers (por ejemplo, dónde hay que empezar a
revisar, algo a lo que hay que poner atención adicional, etc.), todo eso se
puede poner en esta sección.

También si faltan cosas por hacer, se puede hacer un checklist en esta sección.

Si no se utiliza, esta sección se puede eliminar.

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by iqbalcodes6602** [comment]
@pabo99  can you please review this PR and possibly merge it

**Comment by pabo99** [comment]
> @pabo99 can you please review this PR and possibly merge it

Sure!

The original problem here is that the table header has a z-index (because we are using the `sticky-top` class), and the first record on the search list is hidden:

image

So, removing the z-index attribute is good, but you need to overwrite the z-index attribute in the table header.

**Comment by iqbalcodes6602** [comment]
hello @pabo99 sir,
i looked into it have added z-index:1 for  the sticky-top class to overwrite it, and its fine now.

image

would you consider merging it please.

**Comment by iqbalcodes6602** [comment]
hello @pabo99 sir,
i looked into it have added z-index:1 for  the sticky-top class to overwrite it, and its fine now.

image


would you consider merging it please.

**Review by pabo99 — APPROVED** [review]
Looks good to me! 

Thank you @iqbalcodes6602 !

**Comment by iqbalcodes6602** [comment]
> Looks good to me! 
> 
> Thank you @iqbalcodes6602 !

Hello @pabo99 sir, 
Sorry for the linting errors I will fix this definitely. 
Also I want to ask if omeagup will participate in gsoc 2024 or not

**Comment by heduenas** [comment]
@iqbalcodes6602  thank you for your interest. We have sent our application for GSoC, fingers crossed we will be accepted!

**Comment by pabo99** [comment]
@iqbalcodes6602 could you please update your branch? If all the tests are successful, it will be merged automatically with the main branch

**Pull request merged**
