### PR TITLE
Pull Request regarding Correct the text of privacy/accept_teacher

### PR DESCRIPTION
**Pull request by mohdabbas955**
#Description

I have changes the text of es.md and en.md files.

part of https://github.com/omegaup/omegaup/issues/5931

### CODE REVIEW

**Comment by lhchavez** [comment]
The error is legitimate: https://github.com/omegaup/omegaup/runs/5800151940?check_suite_focus=true

can you run that command to fix the issue?

**Comment by mohdabbas955** [comment]
> The error is legitimate: https://github.com/omegaup/omegaup/runs/5800151940?check_suite_focus=true
> 
> can you run that command to fix the issue?

Yes , I have run this command "./stuff/policy-tool.py upgrade" inside container in VS code . Now what should I do next?

**Comment by mohdabbas955** [comment]
I have generated new PR  #6498 after running this command. You can check it. Hopefully It will pass all test and will get merged.

**Comment by lhchavez** [comment]
> I have generated new PR  #6498 after running this command. You can check it. Hopefully It will pass all test and will get merged.

please try not to open new pull requests to make changes to an existing one. just push any new commits to the same branch and the PR will be updated.

**Comment by mohdabbas955** [comment]
> > I have generated new PR  #6498 after running this command. You can check it. Hopefully It will pass all test and will get merged.
> 
> please try not to open new pull requests to make changes to an existing one. just push any new commits to the same branch and the PR will be updated.

Sorry for that,I have deleted that PR.

**Comment by mohdabbas955** [comment]
> The error is legitimate: https://github.com/omegaup/omegaup/runs/5800151940?check_suite_focus=true
> 
> can you run that command to fix the issue?

i have run this command "/stuff/policy-tool.py upgrade". Now what should I do inorder to solve this error and get my PR merged.

**Review by heduenas — APPROVED** [review]
LGTM, defer to @lhchavez

**Review by lhchavez — APPROVED** [review]
will merge on Sunday morning (if there are pending database changes on Saturday we skip the deployment, so we would like to avoid that situation).

**Comment by mohdabbas955** [comment]
Please remember to merge this PR.

**Comment by lhchavez** [comment]
> Please remember to merge this PR.

no need to remind us!

**Pull request merged**
