### PR TITLE
Added test for the action "Rejudge submission"

### PR DESCRIPTION
**Pull request by SubhashThenua**
# Description

This PR added a cypress test for the action **Rejudge submission**

Fixes: #7433 

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.
- [x] If you are creating a feature, the new tests were added.
- [x] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Review by pabo99 — APPROVED** [review]
Excelent job!

Thank you @SubhashThenua !!

**Comment by SubhashThenua** [comment]
Hi, @pabo99 Are there any other user journeys that require Cypress tests?
If yes, then please let me know. I am interested to write more tests.
Thanks!

**Comment by SubhashThenua** [comment]
> > Hi, @pabo99 Are there any other user journeys that require Cypress tests? If yes, then please let me know. I am interested to write more tests. Thanks!
> 
> Sure, let me check if there are more tests you can write, and I'll let you know.
> 
> Thank you in advance!

Just a friendly ping @pabo99. 
Also If there are any other issues then please ping me. I am happy to give try,
 Thanks!

**Review by heduenas — APPROVED** [review]

**Comment by SubhashThenua** [comment]
> > > > Hi, @pabo99 Are there any other user journeys that require Cypress tests? If yes, then please let me know. I am interested to write more tests. Thanks!
> > > 
> > > 
> > > Sure, let me check if there are more tests you can write, and I'll let you know.
> > > Thank you in advance!
> > 
> > 
> > Just a friendly ping @pabo99. Also If there are any other issues then please ping me. I am happy to give try, Thanks!
> 
> Hi @SubhashThenua, sure, we have a couple of new features that will be ready to test soon. Can you first solve the conflicts in the PR you have open yet?

Hi, @pabo99 Sorry for the delay, I have resolved the conflicts in the other PR.
Thanks for finding new features, I am happy to write test for them also.Please open an PR and ping me.
Thanks!

**Pull request merged**
