### PR TITLE
FIX ISSUE :#6975 Remove all references to ArenaV1 #6979

### PR DESCRIPTION
**Pull request by subhajit20**
Description: Remove all references to ArenaV1 FIX-https://github.com/omegaup/omegaup/issues/6975

 Delete the record of the file nginx.rewritesnamed: arenav1.
 Delete the file /arena/index.phpthat will no longer be used.
 Delete the controller function Contestcalled: getContestListDetailsForTypeScript.
 Delete the record of the file webpack.config-frontend.jsnamed: arena_contest_list.
 Delete the file /frontend/www/js/omegaup/arena/contest_list.tsthat will no longer be used.
 Delete the component /components/arena/ContestList.vuethat will no longer be used.
 Delete all tests that call anything from what was previously deleted.

### CODE REVIEW

**Comment by subhajit20** [comment]
hey! @pabo99 kindly check it, I have pushed again all the required changes and let me know if there is any other modifications needed

**Comment by pabo99** [comment]
It looks good. Just one more change:

You need delete the following string tranlations in the .lang files:
```

Error: Translation string 'arenaCurrentContests' not used
Error: Translation string 'arenaCurrentPublicContests' not used
Error: Translation string 'arenaFutureContests' not used
Error: Translation string 'arenaMyActiveContests' not used
Error: Translation string 'arenaOldContests' not used
Error: Translation string 'arenaPageIntroduction' not used
Error: Translation string 'arenaRecommendedCurrentContests' not used
Error: Translation string 'arenaRecommendedOldContests' not used
Error: Translation string 'frontPageIntroduction' not used
Error: Translation string 'frontPageIntroductionButton' not used
Error: Process completed with exit code 1.
```

**Comment by subhajit20** [comment]
> It looks good. Just one more change:
> 
> You need delete the following string tranlations in the .lang files:
> 
> ```
> 
> Error: Translation string 'arenaCurrentContests' not used
> Error: Translation string 'arenaCurrentPublicContests' not used
> Error: Translation string 'arenaFutureContests' not used
> Error: Translation string 'arenaMyActiveContests' not used
> Error: Translation string 'arenaOldContests' not used
> Error: Translation string 'arenaPageIntroduction' not used
> Error: Translation string 'arenaRecommendedCurrentContests' not used
> Error: Translation string 'arenaRecommendedOldContests' not used
> Error: Translation string 'frontPageIntroduction' not used
> Error: Translation string 'frontPageIntroductionButton' not used
> Error: Process completed with exit code 1.
> ```

Sure will do that.

**Comment by subhajit20** [comment]
Hello @pabo99 , now kindly check that I have pushed all the required changes again.

**Comment by pabo99** [comment]
> Hello @pabo99 , now kindly check that I have pushed all the required changes again.

To run the linting script outside the container, use the following command:

```bash
./stuff/lint.sh
```
Please note that you'll need to work on a Linux instance. If you're using Windows, you can use [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install) to work with the required environment.

**Comment by subhajit20** [comment]
Refactoring

**Pull request closed without merging**
