### PR TITLE
Fix missing error highlighting in profile basic information fields

### PR DESCRIPTION
**Pull request by sudarsan2k5**
# Description

These changes will:
1. Add real-time validation of the username field
2. Show a red border when the username contains spaces
3. Prevent form submission when the username is invalid
4. Add a test case to verify this behavior
5. The input field will turn red as soon as a space is detected in the username, and return to normal when the username is valid.

Screenshot 2024-10-31 at 4 14 33 PM

Fixes: #7781 
# Comments

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.

### CODE REVIEW

**Comment by sudarsan2k5** [comment]
Hi @pabo99 , I’ve already fixed this issue. However, I have a question about the style code responsible for the red error highlight on the username input box. Since I couldn’t locate the CSS for basicInformation.vue, I added the CSS directly to the bottom of the same file. Could this approach cause any issues? If there's a better location for this styling, could you suggest the appropriate CSS file where I can place it instead?

**Comment by pabo99** [comment]
Before pushing your changes, please run the following command to fix any linting errors:
```bash
./stuff/lint.sh
```

**Comment by sudarsan2k5** [comment]
Thank you for your review, @pabo99 . I've modified the code as suggested, and it works perfectly. Please let me know if any further modifications are needed.

https://github.com/user-attachments/assets/91faefd0-22b1-4d6a-b621-b79f2c770a8d

**Review by pabo99 — COMMENTED** [review]
It seems that your changes broke a test in `frontend/www/js/omegaup/components/user/BasicInformationEdit.test.ts`. Now that whitespace is no longer allowed, the test `Should emit user update basic information` is failing. Could you please fix it so we can approve this change?

**Comment by sudarsan2k5** [comment]
Thank you for your feedback, @pabo99. I've updated the code based on it. Please let me know if any further changes are needed.

**Review by pabo99 — APPROVED** [review]
Great job! Thank you so much @sudarsan2k5 !!!

**Review by heduenas — APPROVED** [review]

**Pull request merged**
