### PR TITLE
Duplicated entry in array

### PR DESCRIPTION
**Pull request by UlisesGallardo**
# Descripción

En el constructor de la clase DuplicatedEntryInArrayException , el argumento duplicatedItemsInArray ya no tiene valor por defecto, volviendolo obligatorio.

Fixes: #6924

# Comentarios

Fue necesario modificar los siguientes archivos:

https://github.com/omegaup/omegaup/blob/8a8383f75c9dac3c2c5fe069acc3501e6b501df8/frontend/server/src/Controllers/QualityNomination.php#L340,L374
https://github.com/omegaup/omegaup/blob/8a8383f75c9dac3c2c5fe069acc3501e6b501df8/frontend/server/src/Controllers/QualityNomination.php#L340,L374

para que la llamada al constructor tuviera los parametros necesarios.

La clase DuplicatedEntryInArrayException ahora recibe un parametro extra que hace referencia al Item que se está duplicando, ya sea un usuario, un tag, etc.

Se actualizaron la cadenas de traducción del mensaje: duplicateTagsNotAllowed

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [ ] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by pabo99** [comment]
Could you please run `./stuff/lint.sh` in order to fix the linter errors? Then we can review the PR

**Comment by UlisesGallardo** [comment]
> Could you please run `./stuff/lint.sh` in order to fix the linter errors? Then we can review the PR

I ran ./stuff/lint.sh fix -- "files" to fix the linter errors, but git doesn't show any change, is that normal?

**Comment by pabo99** [comment]
> > Could you please run `./stuff/lint.sh` in order to fix the linter errors? Then we can review the PR
> 
> I ran ./stuff/lint.sh fix -- "files" to fix the linter errors, but git doesn't show any change, is that normal?

It's weird, can you show the output when you run the command?

**Comment by UlisesGallardo** [comment]
it didn't show me nothing, this is the command that I ran:
 ./stuff/lint.sh fix -- frontend/server/src/Controllers/QualityNomination.php 
frontend/server/src/Exceptions/DuplicatedEntryInArrayException.php frontend/templates/pseudo.lang frontend/www/js/omegaup/lang.en.json frontend/www/js/omegaup/lang.en.ts frontend/www/js/omegaup/lang.es.json frontend/www/js/omegaup/lang.es.ts frontend/www/js/omegaup/lang.pseudo.json frontend/www/js/omegaup/lang.pseudo.ts frontend/www/js/omegaup/lang.pt.json frontend/www/js/omegaup/lang.pt.ts 

but I also tried ./stuff/lint.sh

**Comment by UlisesGallardo** [comment]
I tried outside and I had this error : docker: Error response from daemon: invalid mode: /Github/omegaup. Because I'm in windows I tried to change the OMEGAUP_ROOT in the lint.sh file but dind't work, I got a new error: fatal: not a git repository (or any of the parent directories): .git

**Comment by UlisesGallardo** [comment]
> Are you running the command outside the container?
> 
> You should view something like:
> 
> image

Now you can run the linter, I couldn't get it to work on the windows repo so I migrated to ubuntu

**Review by pabo99 — APPROVED** [review]
Este cambio se ve bien. Gracias.

**Review by heduenas — APPROVED** [review]

**Pull request merged**
