### PR TITLE
Added sponsor logos to footer

### PR DESCRIPTION
**Pull request by anmode**
# Descripción
Added sponsor logo to footer amazon,f5,replit

Footer now-
WhatsApp Image 2022-04-02 at 6 43 37 AM

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Review by lhchavez — COMMENTED** [review]
looks better! the only remaining thing is that the logo should be a 400x400 image instead of a 600x400 one.

**Comment by anmode** [comment]
> looks better! the only remaining thing is that the logo should be a 400x400 image instead of a 600x400 one.

https://vimeo.com/694714967/dacc3a2842 would u check out this!

**Comment by anmode** [comment]
done I cropped it to 400X400 :)

**Review by lhchavez — COMMENTED** [review]
defer to @tvanessa / @heduenas

**Comment by tvanessa** [comment]
can you add an screenshot of the footer in the description? Please

**Comment by anmode** [comment]
> can you add an screenshot of the footer in the description? Please

Sure!

**Review by tvanessa — APPROVED** [review]

**Comment by anmode** [comment]
Thanks! This is my first contribution to OmegaUp.

**Pull request merged**
