### PR TITLE
Traducido el string Penalty a la hora de crear un contest

### PR DESCRIPTION
**Pull request by ibonkonesa**
Traducido el string Penalty a la hora de crear un contest

### CODE REVIEW

**Comment by lhchavez** [comment]
idealmente, intenta evitar cerrar este PR y volver a crearlo: si empujas cambios a tu rama `master`, se verán reflejados en este PR. así es menos trabajo para tí y no nos llegan tantos correos de PRs abiertos!

**Comment by ibonkonesa** [comment]
Ok, así lo haré!

**Comment by ibonkonesa** [comment]
No hay manera de conseguir que pase le lint: he cambiado el string en los 2 archivos correspondientes y el comando ./stuff/lint.sh fix me dice que ok, no se que puede estar fallando en el action :S 

Alguna sugerencia? Intento ejecutar el comando que el action me sugiere: ./stuff/lint.sh fix -- frontend/www/js/omegaup/lang.es.json frontend/www/js/omegaup/lang.es.ts

pero me da este error:
PHP Fatal error:  require_once(): Failed opening required '/src/frontend/server/cmd/../libs/third_party/log4php/src/main/php/Logger.php' (include_path='.:/usr/share/php') in /src/frontend/server/cmd/APITool.php on line 4

**Comment by lhchavez** [comment]
> No hay manera de conseguir que pase le lint: he cambiado el string en los 2 archivos correspondientes y el comando ./stuff/lint.sh fix me dice que ok, no se que puede estar fallando en el action :S
> 
> Alguna sugerencia? Intento ejecutar el comando que el action me sugiere: ./stuff/lint.sh fix -- frontend/www/js/omegaup/lang.es.json frontend/www/js/omegaup/lang.es.ts
> 
> pero me da este error:
> PHP Fatal error: require_once(): Failed opening required '/src/frontend/server/cmd/../libs/third_party/log4php/src/main/php/Logger.php' (include_path='.:/usr/share/php') in /src/frontend/server/cmd/APITool.php on line 4

seguiste la guía de cómo empezar a colaborar usando Docker? https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar#instalaci%C3%B3n-con-docker

también, según esto ya tenemos un bot que hace linter por tí. déjame veo por qué no se ejecutó

**Comment by ibonkonesa** [comment]
Con ese comando hay mas errores: 

`➜  omegaup git:(master) ./stuff/lint.sh fix --all
stuff/api_linter.py:10:1: [mypy] error: Cannot find implementation or library stub for module named 'hook_tools'
    from hook_tools import linters
    ^
stuff/api_linter.py:10:1: [mypy] note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
    from hook_tools import linters
    ^
stuff/api_linter.py:82:17: [mypy] error: Class cannot subclass 'Linter' (has type 'Any')
    class ApiLinter(linters.Linter):
                    ^
stuff/dao_linter.py:9:1: [mypy] error: Cannot find implementation or library stub for module named 'hook_tools'
    from hook_tools import linters
    ^
stuff/dao_linter.py:9:1: [mypy] note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
    from hook_tools import linters
    ^
stuff/dao_linter.py:12:17: [mypy] error: Class cannot subclass 'Linter' (has type 'Any')
    class DaoLinter(linters.Linter):
                    ^
stuff/dao_linter.py:30:33: [mypy] error: Module has no attribute "util"
            dao_utils_module_spec = importlib.util.spec_from_file_location(
                                    ^
stuff/dao_linter.py:34:21: [mypy] error: Module has no attribute "util"
            dao_utils = importlib.util.module_from_spec(dao_utils_module_spec)
                        ^
stuff/translation_strings_linter.py:9:1: [mypy] error: Cannot find implementation or library stub for module named 'hook_tools'
    from hook_tools import linters
    ^
stuff/translation_strings_linter.py:9:1: [mypy] note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
    from hook_tools import linters
    ^
stuff/translation_strings_linter.py:17:32: [mypy] error: Class cannot subclass 'Linter' (has type 'Any')
    class TranslationStringsLinter(linters.Linter):
                                   ^
PHP Warning:  require_once(/src/frontend/server/cmd/../libs/third_party/log4php/src/main/php/Logger.php): failed to open stream: No such file or directory in /src/frontend/server/cmd/APITool.php on line 4
PHP Fatal error:  require_once(): Failed opening required '/src/frontend/server/cmd/../libs/third_party/log4php/src/main/php/Logger.php' (include_path='.:/usr/share/php') in /src/frontend/server/cmd/APITool.php on line 4
CompletedProcess(args=['/usr/bin/php', '/src/frontend/server/cmd/APITool.php', '--file=api.ts'], returncode=255, stdout='')
Traceback (most recent call last):
  File "/hook_tools/lint.py", line 341, in <module>
    main()
  File "/hook_tools/lint.py", line 311, in main
    local_violations, local_fixable = _run_linter(
  File "/hook_tools/lint.py", line 209, in _run_linter
    _run_linter_all(args, linter, filenames, validate_only,
  File "/hook_tools/lint.py", line 90, in _run_linter_all
    new_file_contents, original_contents, violations = linter.run_all(
  File "/hook_tools/linters.py", line 1010, in run_all
    return self._instance.run_all(filenames, contents_callback)
  File "/src/stuff/api_linter.py", line 99, in run_all
    new_contents, original_contents = _generate_new_contents(
  File "/src/stuff/api_linter.py", line 76, in _generate_new_contents
    new_content=_generate_typescript(os.path.basename(path)),
  File "/src/stuff/api_linter.py", line 40, in _generate_typescript
    result.check_returncode()
  File "/usr/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/usr/bin/php', '/src/frontend/server/cmd/APITool.php', '--file=api.ts']' returned non-zero exit status 255.
`

es extraño que solo cambiar un string cambie el lint, pues no se han generado ni saltos de linea ni cualquier cosa susceptible a ser linteada :/

**Comment by lhchavez** [comment]
> Con ese comando hay mas errores:
>  ...
> 
> es extraño que solo cambiar un string cambie el lint, pues no se han generado ni saltos de linea ni cualquier cosa susceptible a ser linteada :/

ah es que nosotros llamamos "lint" a muchas más cosas, como re-generar los archivos de traducción. en este caso en particular, parece que lo que falta es mandar llamar `git submodule update --init`. alternativamente, en vez de `fix --all`, usa el comando que aparece aquí: https://github.com/omegaup/omegaup/actions/runs/324926830

```shell
./stuff/lint.sh fix -- frontend/www/js/omegaup/lang.es.json frontend/www/js/omegaup/lang.es.ts
```

**Review by lhchavez — APPROVED** [review]
:tada:

**Pull request merged**
