### PR TITLE
[Important_Feature]Migrate to Google Identity Services

### PR DESCRIPTION
**Pull request by anmode**
1. Removed the old library `gapi.auth2`

fixes: #6915

Just made this pR. So to track that it is going in right way.

### CODE REVIEW

**Comment by heduenas** [comment]
@anmode please let us know when this is ready for review!

**Comment by anmode** [comment]
> @anmode please let us know when this is ready for review!

Sure! Ig there would be descent changes🥲. I have to take help.

**Comment by anmode** [comment]
I'm Writing some of my research and what i figure out as changes would be descent!
files need to be modified:
https://github.com/anmode/omegaup/blob/google/frontend/www/js/omegaup/login/logout.ts#L22 - Here we used old method as `gapi.auth2.init` and this should be updated by `initTokenClient() or initCodeClient()`
https://github.com/anmode/omegaup/blob/google/frontend/www/js/omegaup/components/login/Login.vue#L84

Ig this should remain as it is - https://github.com/anmode/omegaup/blob/google/frontend/server/src/Controllers/Session.php#L509

I have already changes the script as here - https://github.com/anmode/omegaup/blob/google/frontend/server/src/Controllers/User.php#L606
https://github.com/anmode/omegaup/blob/google/frontend/www/logout.php#L16

I think only these two files need to be changed to adapt `logout.ts` and `login.vue`.

**Comment by anmode** [comment]
closing as pR opened for perfect solution- #6936 Thanks!

**Pull request closed without merging**
