### PR TITLE
[ArenaV2] Improve message when list is empty 

### PR DESCRIPTION
**Pull request by anmode**
# Description

I have done changes in language which is predefined templates.
omegaupareanav2

This PR fixes one part of the issue that mainly focused on text,

Part of: #6493 

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by anmode** [comment]
I guess by mistake I had done two same commit :(. Sorry for that.

**Comment by lhchavez** [comment]
hmm this PR seems to be empty (there are no files changed)

**Comment by anmode** [comment]
> hmm this PR seems to be empty (there are no files changed)

Ohh so I'll commit next

**Comment by heduenas** [comment]
Can you update `es.lang` and `pt.lang` as well? For ES you can use the message written in the description of https://github.com/omegaup/omegaup/issues/6493, for PT you can use the google translate translation.

**Comment by anmode** [comment]
> Can you update `es.lang` and `pt.lang` as well? For ES you can use the message written in the description of #6493, for PT you can use the google translate translation.

idk but i am unable to find these files in the codebase. I have searched a lot.
could u tell please?

**Comment by pabo99** [comment]
> > Can you update `es.lang` and `pt.lang` as well? For ES you can use the message written in the description of #6493, for PT you can use the google translate translation.
> 
> idk but i am unable to find these files in the codebase. I have searched a lot. could u tell please?

Those files are located in the same directory:
- `frontend/templates/es.lang`
- `frontend/templates/pt.lang`

**Comment by anmode** [comment]
> > > Can you update `es.lang` and `pt.lang` as well? For ES you can use the message written in the description of #6493, for PT you can use the google translate translation.
> > 
> > 
> > idk but i am unable to find these files in the codebase. I have searched a lot. could u tell please?
> 
> Those files are located in the same directory:
> 
>     * `frontend/templates/es.lang`
> 
>     * `frontend/templates/pt.lang`

oh yes! Oops sorry. Thanks

**Comment by anmode** [comment]
done!

**Review by heduenas — APPROVED** [review]
LGTM, defer to @lhchavez

**Pull request merged**
