### PR TITLE
Added Cypress test  for Disqualify and Requalify submission

### PR DESCRIPTION
**Pull request by SubhashThenua**
# Description

Added Cypress test for Disqualify and Requalify Submission.

If you modify the **User Interface**, please include a screenshot or a video.

Fixes: [#7432](https://github.com/omegaup/omegaup/issues/7432)

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.
- [x] If you are creating a feature, the new tests were added.
- [x] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Review by pabo99 — APPROVED** [review]
LGTM! 

Thank you @SubhashThenua

**Comment by SubhashThenua** [comment]
Thank you so much @pabo99 for the review. Can you please merge this?

**Review by heduenas — APPROVED** [review]

**Comment by heduenas** [comment]
@SubhashThenua can you please resolve the conflicts that emerged? after that, we'll be ready to merge your pr.

**Comment by SubhashThenua** [comment]
Hi, @heduenas Please take a look.
Thanks!

**Comment by SubhashThenua** [comment]
Hi @heduenas, can you please merge this to avoid any potential conflicts in the future?

**Comment by heduenas** [comment]
Sorry about the delay @SubhashThenua and thanks for adding this test.

**Pull request merged**
