### PR TITLE
Revert build-containers.yml

### PR DESCRIPTION
**Pull request by heduenas**
# Description

The last change broke the workflow. I'm reverting the for now, we can still try to make the change again.

Fixes: #(issue)

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by pabo99** [comment]
¿Cuál fue el motivo de revertir este cambio?

**Comment by heduenas** [comment]
> ¿Cuál fue el motivo de revertir este cambio?

Se rompio el workflow: https://github.com/omegaup/omegaup/actions/runs/8627109790/job/23646466293

**Comment by heduenas** [comment]
Screenshot 2024-04-10 at 12 08 29 AM
se rompio justamente apartir de estos cambios

**Review by pabo99 — APPROVED** [review]
Oh, entiendo.

Por lo pronto habrá que dejarlo como estaba entonces

**Pull request merged**
