### PR TITLE
Refactor/ephemeral store templates golden layout settings

### PR DESCRIPTION
**Pull request by HNOONa-0**
# Description

Moved some parts of `ephemeral.js` into separate files. The high line count is from just moving things around, I did not add any new functionality.

Fixes: #7620

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.
- [x] If you are creating a feature, the new tests were added.
- [x] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by HNOONa-0** [comment]
Hey @pabo99, I know that submitting pull requests with a high line count is discouraged. But changes I made are primarily for code reorganization and refactoring, without introducing any breaking changes. Would pull requests like these be acceptable?

**Comment by pabo99** [comment]
> Hey @pabo99, I know that submitting pull requests with a high line count is discouraged. But changes I made are primarily for code reorganization and refactoring, without introducing any breaking changes. Would pull requests like these be acceptable?

In that case, the pull request can contain more than 200 modified lines, so the review might take longer than usual.

**Comment by heduenas** [comment]
> > Hey @pabo99, I know that submitting pull requests with a high line count is discouraged. But changes I made are primarily for code reorganization and refactoring, without introducing any breaking changes. Would pull requests like these be acceptable?
> 
> In that case, the pull request can contain more than 200 modified lines, so the review might take longer than usual.

**Comment by heduenas** [comment]
> Hey @pabo99, I know that submitting pull requests with a high line count is discouraged. But changes I made are primarily for code reorganization and refactoring, without introducing any breaking changes. Would pull requests like these be acceptable?

This is fine since you are just moving lines around. Did you test the changes locally? I don't think we have many automated tests for the ephemeral so we will have to rely on manual testing more. heavily than with other components.

**Comment by HNOONa-0** [comment]
> > Hey @pabo99, I know that submitting pull requests with a high line count is discouraged. But changes I made are primarily for code reorganization and refactoring, without introducing any breaking changes. Would pull requests like these be acceptable?
> 
> This is fine since you are just moving lines around. Did you test the changes locally? I don't think we have many automated tests for the ephemeral so we will have to rely on manual testing more heavily than with other components.

Yes I tested submissions locally for interactive and non-interactive problems and both are working. There are bugs however I noticed with stable (main branch) version and I will make issues for them.
Later we will write tests that test logic and submissions through the editor.

**Review by heduenas — APPROVED** [review]

**Pull request merged**
