### PR TITLE
Change initial language of `interactiveIdlSettings`

### PR DESCRIPTION
**Pull request by HNOONa-0**
# Description

The problem was that  the initial language was being set to `idl`, but that language is not present in `supportedLanguages` **(should it be?)**.
Screenshot from 2024-06-03 18-00-49
I changed initial language to `c`, which fixed the problem.

Fixes: #7629

# Comments

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.

### CODE REVIEW

**Comment by HNOONa-0** [comment]
@pabo99 is `idl` still a language that still being used to solve problems on the platform?

**Comment by pabo99** [comment]
> @pabo99 is `idl` still a legitimate language that still being used to solve problems on the platform? I could not find any interactive problems that have that language as an `option`.

I'm not sure. Maybe @heduenas can help us resolve this question.

**Review by heduenas — APPROVED** [review]

**Comment by heduenas** [comment]
I think your change looks good as is and I don't think we need to add `idl` to the list of supported languages.

**Comment by HNOONa-0** [comment]
I think I have a better idea on how to set `initialLanguage` for the editor in general. I'm closing this temporarily.

**Comment by HNOONa-0** [comment]
> I think your change looks good as is and I don't think we need to add `idl` to the list of supported languages.

I think I have a better idea on how to set `initialLanguage` for the editor in general. I'm closing this temporarily.

**Comment by heduenas** [comment]
@HNOONa-0 is this PR still relevant?

**Comment by HNOONa-0** [comment]
> @HNOONa-0 is this PR still relevant?

Yes. Sorry, this change should have been included in another pull request, but I didn't want to further confuse the reviewers.

**Comment by HNOONa-0** [comment]
I closed this pull request because fixing this bug seems to cause another bug. After fixing, the IDE has 3 open tabs for coding instead of 1.
image

**Pull request closed without merging**
