### PR TITLE
fix  for login button's position using css display property

### PR DESCRIPTION
**Pull request by YannyTwoo**
# Descripción

Fixes: #6534 

Previously:
Screenshot 2023-03-08 at 1 15 20 PM
Screenshot 2023-03-08 at 1 15 30 PM

Now:
Screenshot 2023-03-08 at 11 48 17 PM
Screenshot 2023-03-08 at 11 48 34 PM

# Comentarios

1. Repositioned the logout btn by putting it inside the navbar at the end, so it shows up at the far right. 
2. Then created a new div which has another logout btn and the hamburger dropdown menu.

Each is controlled by the css display property. (1) shows when screen size > lg and (2) renders when screen size < lg
lg is bootstrap shorthand for 992px

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by heduenas** [comment]
@pabo99 can you please review this PR?

**Review by pabo99 — COMMENTED** [review]
LGTM. 

Just one comment:

The errors displayed on Github could be fixed if you run:
```bash
./stuff/lint.sh
```
outside the container.

**Comment by pabo99** [comment]
> Ok. Running and fixing up.

Excelent! Now you can commit the new changes.

**Comment by YannyTwoo** [comment]
I'm getting a "detected dubious ownership in repository at '/opt/omegaup'". This doesn't have anything to do with the issue but could you suggest a solution, can't find a fix and push the changes.
(On an arm chip)

**Comment by YannyTwoo** [comment]
Hi, I'm creating a new PR for the same issue. Apologies for the inconvenience.

**Comment by YannyTwoo** [comment]
The selenium test failed on a file I haven't changed. Any suggestion on how I can resolve and commit this?

**Comment by pabo99** [comment]
> The selenium test failed on a file I haven't changed. Any suggestion on how I can resolve and commit this?

Don't worry about this error. We still have some flaky tests, but they can be fixed easily by running the workflows again

**Comment by YannyTwoo** [comment]
Ah ok I see.

**Comment by anmode** [comment]
LGTM!

**Review by anmode — COMMENTED** [review]
LGTM!

**Review by heduenas — APPROVED** [review]

**Pull request merged**
