### PR TITLE
[AreanaV2] Request for Launch of new version Arena.

### PR DESCRIPTION
**Pull request by anmode**
# Descripción
Launch of ArenaV2

Fixes: #6494

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by lhchavez** [comment]
that cypress error is legitimate and seems to be caused by this change.

**Comment by anmode** [comment]
> that cypress error is legitimate and seems to be caused by this change.

So what i supposed to do now?

**Comment by lhchavez** [comment]
> > that cypress error is legitimate and seems to be caused by this change.
> 
> Ohh okay! So what i supposed to do now? 

the cypress test in question needs to be updated to be compatible with arena v2 since it was written for arena v1

**Comment by anmode** [comment]
> > > that cypress error is legitimate and seems to be caused by this change.
> > 
> > 
> > Ohh okay! So what i supposed to do now?
> 
> the cypress test in question needs to be updated to be compatible with arena v2 since it was written for arena v1

okay got it! Just a small help So i have to modify `basic_commands.spec.ts` in cypress folder and to add element `a[data-contests]` isn;t it ? like this `cy.get('[data-contests]').click();` .

**Comment by lhchavez** [comment]
> > > > that cypress error is legitimate and seems to be caused by this change.
> > > 
> > > 
> > > Ohh okay! So what i supposed to do now?
> > 
> > the cypress test in question needs to be updated to be compatible with arena v2 since it was written for arena v1
> 
> okay got it! Just a small help So i have to modify `basic_commands.spec.ts` in cypress folder and to add element `a[data-contests]` isn't it ? like this `cy.get('[data-contests]').click();` .  

probably. for further help, please ask on Discord!

**Review by lhchavez — APPROVED** [review]

**Pull request merged**
