### PR TITLE
Footer alignment

### PR DESCRIPTION
**Pull request by sudarsan2k5**
# Description

- Added mt-5 class to the `<footer> `element to create a top margin, ensuring the footer is properly spaced from the above content.
- Added mt-3 class to the `<div class="copy">` element to provide additional spacing within the footer, enhancing its visual separation from the rest of the page.

https://github.com/user-attachments/assets/0b1749a0-d727-469b-9fa8-d946a644b22d

Fixes: #7895 

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.

### CODE REVIEW

**Comment by sudarsan2k5** [comment]
@pabo99 I have resolved this issue. Please let me know if you need any further changes.

**Comment by heduenas** [comment]
@sudarsan2k5 for PRs like these can you please include an screenshot/video of the mobile version?

**Comment by sudarsan2k5** [comment]
Tested on iPad:-

https://github.com/user-attachments/assets/8df74b09-6d64-49a3-8888-37f8e2d097d6

Tested on Mobile:-


https://github.com/user-attachments/assets/d39ffe13-2089-4445-8bb1-5c536b0a6c69


Thank you for your response @heduenas, I checked both iPad and mobile, and it's working fine. but let me know if you have any suggestions.

**Review by pabo99 — APPROVED** [review]
LGTM!

**Review by heduenas — APPROVED** [review]

**Pull request merged**
