### PR TITLE
FIX ISSUE :#6975 Remove all references to ArenaV1

### PR DESCRIPTION
**Pull request by subhajit20**
Description: Remove all references to ArenaV1 FIX-https://github.com/omegaup/omegaup/issues/6975

Delete the record of the file nginx.rewritesnamed: arenav1.
Delete the file /arena/index.phpthat will no longer be used.
Delete the controller function Contestcalled: getContestListDetailsForTypeScript.
Delete the record of the file webpack.config-frontend.jsnamed: arena_contest_list.
Delete the file /frontend/www/js/omegaup/arena/contest_list.tsthat will no longer be used.
Delete the component /components/arena/ContestList.vue that will no longer be used.
Delete all tests that call anything from what was previously deleted.

### CODE REVIEW

**Comment by subhajit20** [comment]
hey @pabo99 I have pushed and with all required changes and this time my vs code lint was disable.
can you review my pr once ?

**Review by pabo99 — APPROVED** [review]
LGTM.

Thanks for helping us with this PR

**Comment by subhajit20** [comment]
> LGTM.
> 
> Thanks for helping us with this PR

Hey Thanks!

would you merge this chages with the main branch ?

**Comment by subhajit20** [comment]
Finally, It got all the checks done .
hey @pabo99  would you merge this branch?

**Comment by pabo99** [comment]
> > LGTM.
> > Thanks for helping us with this PR
> 
> Hey Thanks!
> 
> would you merge this chages with the main branch ?

Defer to: @heduenas

**Comment by subhajit20** [comment]
> > > LGTM.
> > > Thanks for helping us with this PR
> > 
> > 
> > Hey Thanks!
> > would you merge this chages with the main branch ?
> 
> Defer to: @heduenas

Sorry! I do not understand exactly what ?

**Review by heduenas — APPROVED** [review]

**Pull request merged**
