### PR TITLE
Remove scroll CSS styles from ContestListv2.vue

### PR DESCRIPTION
**Pull request by iqbalcodes6602**
# Description

After reading some of the previous commits this was also asked to be fixed previously, but wasn't done correctly. I have removed the styles for scroll-content, hence enablin the height to be auto.

image

here it is displaying 10 contest yet no scrolls

Fixes: #7516 

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by pabo99** [comment]
The reason for deciding to set a maximum height for the contest list was precisely to ensure that the search, sorting, and filtering controls were always visible. However, this wasn't being achieved.

Is there a way to stick the control bar to the top of the page even when scrolling down? We previously attempted to use CSS styles with position: sticky, but perhaps we were doing it incorrectly.

Could you try adding that behavior?

**Comment by iqbalcodes6602** [comment]
@pabo99  done as you  said

image

**Review by pabo99 — APPROVED** [review]
Excellent! Thank you so much!

**Comment by iqbalcodes6602** [comment]
another thing currently the problems page is also having the same nested scrollers, should i also do that in another PR,. 
The main challenge though  in this is the that we need to fix the pagination part in the bottom and search and all at top.
do u have any suggestion regarding this.
image

**Comment by iqbalcodes6602** [comment]
> Excellent! Thank you so much!

@pabo99 
another thing currently the problems page is also having the same nested scrollers, should i also do that in another PR,.
The main challenge though in this is the that we need to fix the pagination part in the bottom and search and all at top.
do u have any suggestion regarding this.
image

**Comment by pabo99** [comment]
> > Excellent! Thank you so much!
> 
> @pabo99 another thing currently the problems page is also having the same nested scrollers, should i also do that in another PR,. The main challenge though in this is the that we need to fix the pagination part in the bottom and search and all at top. do u have any suggestion regarding this. image

Please assist us in creating the issue. We will continue all discussions in the new thread. Regarding the pagination, I don't think it's necessary to keep it sticky.

**Review by heduenas — APPROVED** [review]

**Pull request merged**
