### PR TITLE
Adding DISTINCT with select query to fetch unique records

### PR DESCRIPTION
**Pull request by tahirs95**
Fixes: #1214

### CODE REVIEW

**Comment by heduenas** [comment]
@tahirs95 Can you plesae tag the bug that you are solving with this PR?

**Comment by tahirs95** [comment]
@heduenas  I have tagged you.

**Comment by lhchavez** [comment]
@heduenas means adding `Fixes: #xx`" to the description, where `xxx` is the id of the iise.

**Comment by tahirs95** [comment]
@lhchavez  I don't know how to add fixes.

**Comment by NdubuisiO** [comment]
@tahirs95 this pull request is a fix for an issue right? Just add the issue that your pull request fixes to the commit message. For example    "Adding DISTINCT with select query to fetch unique records  this pull request fixes issue #1234"

**Comment by NdubuisiO** [comment]
@tahirs95 this pull request is a fix for an issue right? Just add the issue that your pull request fixes to the commit message. For example    "Adding DISTINCT with select query to fetch unique records  this pull request fixes issue #1234679"

**Comment by lhchavez** [comment]
What @NdubuisiO said. Although we prefer to have the Issue that's being fixed in the description of the pull request. That way the title is not crazy long and does not get truncated.

For example: https://github.com/omegaup/omegaup/pull/1852 mentions `Fix #1851` in the description.

**Comment by lhchavez** [comment]
The change itself looks good, though! Once you update the description, I'll merge it :dagger:

**Comment by heduenas** [comment]
The issue is #1214. @tahirs95 please add "Fix #1214" to your PR title.

**Comment by lhchavez** [comment]
nit: to the description instead of the title :D

**Comment by tahirs95** [comment]
@lhchavez @heduenas  I have updated PR title.

**Pull request merged**
