### PR TITLE
initial ephemeral ts

### PR DESCRIPTION
**Pull request by HNOONa-0**
# Description
I downloaded the `goldenLayout` package  instead of using a script tag for importing. I imported the newly merged TypeScript components, everything is working as intended. I modified the components to import the Vuex `store` variable directly rather than passing it as a prop.
I added a new grader config file to compile the typescript version of the components.

https://github.com/user-attachments/assets/071c8820-4bcd-420a-9be2-bde5281af145

Fixes: #7710

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by HNOONa-0** [comment]
@pabo99 PTAL!

**Comment by HNOONa-0** [comment]
@pabo99 Why do we check for attribute presence using this method?
https://github.com/omegaup/omegaup/blob/ba91f88d551b84ec5b34199daaf33d60cc6b25ef/frontend/www/js/omegaup/grader/GraderStore.js#L279-L281
Are there advantages to using this method over **optional chaining**?

**Comment by pabo99** [comment]
> @pabo99 Why do we check for attribute presence using this method?
> 
> https://github.com/omegaup/omegaup/blob/ba91f88d551b84ec5b34199daaf33d60cc6b25ef/frontend/www/js/omegaup/grader/GraderStore.js#L279-L281
> 
> 
> Are there advantages to using this method over **optional chaining**?

I guess that code is legacy, so using the **optional chaining** method should be the best alternative in this case.

**Comment by HNOONa-0** [comment]
@pabo99 PTAL! This is an initial file that will help me work on other issues and testing with the store.

**Review by pabo99 — APPROVED** [review]
It seems that most of the comments will be related to the data types in the `ephemeral.ts` file, but since adding them is not being considered in this change, this PR can be merged into the main branch to unblock the following PRs you will be working on.

**Comment by pabo99** [comment]
PTAL @heduenas !

**Review by heduenas — APPROVED** [review]

**Pull request merged**
