### PR TITLE
Fix dropdown menu overflow and add smooth scrolling for better user experience

### PR DESCRIPTION
**Pull request by k-vijay-05**
# Description

Added functionality to enable smooth scrolling within the dropdown menu, allowing users to access content that was previously hidden due to overflow.

Fixes: #7926 

Video: 

https://github.com/user-attachments/assets/2911df7d-7ecd-4398-b7fb-f2390e5ccacc

Video: (Mobile version)

https://github.com/user-attachments/assets/6143c595-11e6-4d60-9342-3c54dacb1b58

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.

### CODE REVIEW

**Comment by pabo99** [comment]
Why did you close the PR? :disappointed:

**Comment by k-vijay-05** [comment]
@pabo99 I closed the PR because the Cypress tests failed, and I thought there might be an issue in my code. Could you please help me understand the reason for the test failure?

**Comment by pabo99** [comment]
Of course, I'm happy to help! The error wasn't caused by your code but rather by an issue when trying to start the Docker containers in the GitHub workflows. This tends to happen when we lack proper validations, but since it's sporadic, it's not easy to fix completely. The way to handle it is simply by re-running the failed tests.

Even if the error were related to your proposed changes, that's what reviews are for. There's no need to close a PR unless the branch is in an unstable state that can't be easily restored to its ideal state.

**Comment by k-vijay-05** [comment]
@pabo99 Thank you for clarifying! I’ll keep in mind that sporadic failures are possible. I’ve reopened the PR

**Pull request closed without merging**
