### PR TITLE
[BUG] User able to register via not checking the privacy policy

### PR DESCRIPTION
**Pull request by anmode**
# Descripción

https://user-images.githubusercontent.com/88332977/227778317-a1dfe234-326a-4bb1-84d6-f2efcc399b4c.mov

# Checklist:

- [ ] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [ ] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by heduenas** [comment]
Thanks for finding this issue and sending the fix @anmode!
It seems that cypress and selenium tests are now failing, probably because we have tests for the user sign up scenario and we need to update them to account for the privacy policy checkbox.

**Comment by anmode** [comment]
> Thanks for finding this issue and sending the fix @anmode!
> It seems that cypress and selenium tests are now failing, probably because we have tests for the user sign up scenario and we need to update them to account for the privacy policy checkbox.

Ohh okayy! I'll check on my local these test. If this is needs to fixed I'll continue to fix in this pR!
As there are many flaky test too.
If you agree I'll work on these flaky test 
I see these are creating problem these days lol.

**Comment by pabo99** [comment]
This issue has been resolved in PR #6695, but it's a good idea to split the other PR into smaller changes. Could you analyze which changes can be moved to this PR to fix the tests?

Also, you could move the file frontend/www/js/omegaup/components/login/Signup.test.ts to this PR.

**Comment by anmode** [comment]
> This issue has been resolved in PR #6695, but it's a good idea to split the other PR into smaller changes. Could you analyze which changes can be moved to this PR to fix the tests?
> 
> Also, you could move the file frontend/www/js/omegaup/components/login/Signup.test.ts to this PR.

Oops lol..
You are correct how could i forget birthday date pR solved that.😂
Sure...I'll analyze changes nd continue fixing test in this pR!

Sure I'll move!

**Comment by pabo99** [comment]
The PR #7397 attempts to solve the same issue. So, it can be closed in favor of the other one.

**Pull request closed without merging**
