### PR TITLE
The string in the rank table has been fixed (#6939).

### PR DESCRIPTION
**Pull request by devbrianmedina**
# Descripción

Se han actualizado las cadenas de texto
Ingles
image
portugués
image

Fixes: #6939 

# Comentarios

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Comment by anmode** [comment]
Good, I think! Changes to be made in other translations too.
Portuguese nd spanish.

**Comment by heduenas** [comment]
+1 to @anmode's comment. Let's update the English and Portuguese versions as well.

**Comment by devbrianmedina** [comment]
@heduenas I think it's good I'll update the texts in Portuguese

**Review by heduenas — APPROVED** [review]

**Comment by devbrianmedina** [comment]
@heduenas Why were some checks unsuccessful?

**Comment by anmode** [comment]
What about Spanish language ? please fix that translation string too!
And for python test i didn't think your pR creating any issue. 
I'll check on my local!

**Comment by devbrianmedina** [comment]
@anmode The Spanish language string does not require any changes :)

**Comment by devbrianmedina** [comment]
@heduenas  Could you please re-run the tests, I really don't understand why it failed.

**Comment by anmode** [comment]
> @anmode The Spanish language string does not require any changes :)

Ohh ok! That's cool then

**Comment by devbrianmedina** [comment]
@heduenas @anmode @pabo99  I have noticed that in the latest "pull requests" the Python test has failed. After doing some research, I found out that they disabled one of the failing tests, but it could still fail regardless. #6937

**Pull request merged**
