### PR TITLE
added checkbox to accept privacy policy

### PR DESCRIPTION
**Pull request by anmode**
fixes: #6613 
Look like-
Screenshot (30)

# Checklist:
- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Review by heduenas — APPROVED** [review]
We don't have a privacy policy written yet. We will need to get it written down and then add a link from the sign up form to it. But your change LGTM.

**Review by heduenas — COMMENTED** [review]
Can you remove the text on the left and change the checkbox label to "I have read and accept the site's Use and Privacy Policy, as well as the Code of Conduct."?

**Comment by anmode** [comment]
> 

done!

**Review by lhchavez — COMMENTED** [review]
there' s one more lint failure that needs addressing. you can delete that translation string to get the linter to pass

**Comment by anmode** [comment]
> there' s one more lint failure that needs addressing. you can delete that translation string to get the linter to pass

Oh got it. I'll remove that!

**Pull request merged**
