### PR TITLE
Fix showFeedbackForm sync issue in Course.vue and FeedbackCodeView.vue

### PR DESCRIPTION
**Pull request by iqbalcodes6602**
# Description

Added a global variable for changing the visiblity of textarea for adding review by the reviewer for feedback

Fixes: #7465

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

### CODE REVIEW

**Comment by iqbalcodes6602** [comment]
hello @pabo99 
i had some doubt here, the functionning is wroking correctly just some minor fixes are remaining. When i am placing the textarea component for writing the comments it still appears at the top, else the its is working perfectly

**Comment by iqbalcodes6602** [comment]
Also u think I should merge the two components for the review and textarea since they are using same array list and needs to work together?

**Comment by pabo99** [comment]
> Also i think I should merge the two components for the review and textarea since they are using same array list and needs to work together?

Merging the two components seems like a good idea. How difficult do you think that proposed change might be? 

You can split the change into several parts if the number of modified lines exceeds the recommended size (200 lines)

**Comment by iqbalcodes6602** [comment]
> > Also i think I should merge the two components for the review and textarea since they are using same array list and needs to work together?
> 
> Merging the two components seems like a good idea. How difficult do you think that proposed change might be? 
> 
> You can split the change into several parts if the number of modified lines exceeds the recommended size (200 lines)

Ya i can go for it I don't think it would take a lot of time, will definitely try for it.

**Comment by iqbalcodes6602** [comment]
@pabo99 can u give it a look and provide some suggestion on how to fix these failing tests?

**Pull request closed without merging**
