### PR TITLE
 Added clear button in ArenaV2 page

### PR DESCRIPTION
**Pull request by anmode**
# Descripción
I have made it simple and it looks great just. It could have made better using JQuery but it just increases code.
If there any suggestion I will implement those.

Fixes: #6496

# Comentarios
Attached the demo video.

https://user-images.githubusercontent.com/88332977/161783876-56bc361e-315b-433d-a196-c374f17198e1.mp4

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

### CODE REVIEW

**Review by lhchavez — COMMENTED** [review]
> It could have made better using JQuery but it just increases code.

we've worked very hard to remove jQuery from most of the codebase, we'd rather not have it come back ^^;;

btw, the `stuff/hook_tools` was accidentally added. would it be possible to revert it? folks in discord can help with that.

**Comment by anmode** [comment]
> > It could have made better using JQuery but it just increases code.
> 
> we've worked very hard to remove jQuery from most of the codebase, we'd rather not have it come back ^^;;
> 
> btw, the `stuff/hook_tools` was accidentally added. would it be possible to revert it? folks in discord can help with that.

Ok I'll ask, how to revert it!

**Comment by anmode** [comment]
> > > It could have made better using JQuery but it just increases code.
> > 
> > 
> > we've worked very hard to remove jQuery from most of the codebase, we'd rather not have it come back ^^;;
> > btw, the `stuff/hook_tools` was accidentally added. would it be possible to revert it? folks in discord can help with that.
> 
> ohh I also didn't use jquery and I'll ask, how to revert it!

**Comment by anmode** [comment]
Done!

**Comment by anmode** [comment]
> > It could have made better using JQuery but it just increases code.
> 
> we've worked very hard to remove jQuery from most of the codebase, we'd rather not have it come back ^^;;
> 
> btw, the `stuff/hook_tools` was accidentally added. would it be possible to revert it? folks in discord can help with that.

I have done it! Please review I think i had reverted the commit successfully.

**Comment by pabo99** [comment]
One question: 

How difficult could be reset the query in the URL? I mean, if I had the following URL:

https://omegaup.com/arenav2/?query=icpc#past

when I press "close" button, the URL changes to: 

https://omegaup.com/arenav2/?query=#past
?

It's like "Search" button has been triggered

**Comment by anmode** [comment]
> One question:
> 
> How difficult could be reset the query in the URL? I mean, if I had the following URL:
> 
> https://omegaup.com/arenav2/?query=icpc#past
> 
> when I press "close" button, the URL changes to:
> 
> https://omegaup.com/arenav2/?query=#past ?
> 
> It's like "Search" button has been triggered

I think for that I have to use JQuery It seems simple for me 
But yeah here by pressing the close button Url isn't changes only the keyword typed in search bar reset.
But triggering of search button is different from close button.
I just made it like http://dflourusso.com.br/v-reset-input/
If I am wrong anywhere! Then Please guide a little.

**Comment by heduenas** [comment]
If it's rather expensive to also clear the fields in the URL then I'd say let's leave it is right now and file a bug to do the URL improvement later on.

**Review by heduenas — APPROVED** [review]
LGTM

**Comment by anmode** [comment]
> If it's rather expensive to also clear the fields in the URL then I'd say let's leave it is right now and file a bug to do the URL improvement later on.

Yeah Sure! I'll do that when it is required to do so
Thanks!

**Pull request merged**
